    <div class="container">
        <h1>Listagem de contatos</h1>
        <table class="table">
            <thead>
                <tr>
                    <th class="text-center">id</th>
                    <th>Produto</th>
                    <th>Descrição</th>
                    <th>Valor</th>
                    <th>Quantidade</th>
                    <th class="text-center">Ações</th>
                </tr>
            </thead>
            <tbody id="listagem">
                <tr id="filtro">
                    <td class="col-lg-1"><input type="text" class="form-control" id="filtroId"></td>
                    <td class="col-lg-2"><input type="text" class="form-control" id="filtroNome"></td>
                    <td><input type="text" class="form-control" id="filtroDescricao"></td>
                    <td><input type="text" class="form-control" id="filtroValor"></td>
                    <td><input type="text" class="form-control" id="filtroQuantidade"></td>
                    <td>&nbsp;</td>
                </tr>
            </tbody>
        </table>
    </div>
    <!-- Modal Detalhe Produto-->
    <div class="modal fade" id="modalProdutoEditar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Detalhes do produto</h4>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="nomeProduto">Produto: </label>
                            <input type="text" class="form-control" id="nomeProduto" required>
                        </div>
                        <div class="form-group">
                            <label for="descricaoProduto">Descrição: </label>
                            <input type="text" class="form-control" id="descricaoProduto" required>
                        </div>
                        <div class="form-group">
                            <label for="valorProduto">Valor: </label>
                            <input type="text" class="form-control" id="valorProduto" required>
                        </div>
                        <div class="form-group">
                            <label for="quantidadeProduto">Quantidade: </label>
                            <input type="text" class="form-control" id="quantidadeProduto" required>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
    <script src="/jquery/jquery-3.2.1.min.js"></script>
    <script src="/bootstrap/js/bootstrap.js"></script>
    <script src="/js/viewListagem.js"></script>